### ISSUE TITLE
Harden Nginx proxy manager

### ISSUE THREAD

**Issue by RobotsAreCrazy** [LordZeuss/auto-authelia#1]
Hi, 
I found this guide https://beaglesecurity.com/blog/article/nginx-server-security.html
Can you add these fixes to nginx is it possible?
Thanks

**Comment by LordZeuss** [comment]
After looking at the article, the code doesn't seem to apply to the configuration part for NPM, which is what mine is setup for. It's designed for nginx, not NPM. (The lines they suggest changing, don't exist in my code)

If I'm able to implement regular nginx, I'll consider adding these changes, but ultimately the goal of the project is to have a simple was to install and configure authelia quickly, not change the default security. Although more security never hurts, I want the end user to be able to change what they want and just use the script for an accelerated start.

Thank you for the suggestion!
