### ISSUE TITLE
Changes to Script.

### ISSUE THREAD

**Issue by wlatic** [LordZeuss/auto-authelia#2]
This works well, however one setting generates incorrectly in the default config:

regulation:
  max_retries: 5m

But this should be:

regulation:
  max_retries: 5

**Comment by LordZeuss** [comment]
> This works well, however one setting generates incorrectly in the default config:
> 
> regulation:
>   max_retries: 5m
> 
> But this should be:
> 
> regulation:
>   max_retries: 5

You're right. I must've accidentally changed this when doing updates. I'll fix this ASAP. Thanks!

**Comment by LordZeuss** [comment]
Issue has been fixed. Thanks!
