### ISSUE TITLE
Time Zone set to America/Chicago by default

### ISSUE THREAD

**Issue by leightonc1** [LordZeuss/auto-authelia#3]
The Time Zone is set to America/Chicago by default in the docker-compose file that's created by the script. It's simple enough to fix manually, but wasn't noticed on my first run so I had to re-run the script after editing.

**Comment by LordZeuss** [comment]
You should be able to edit the docker-compose.yml file that is created by the script to change the time zone without having to edit the script to do it. I'll add a note in the notes for this, so people know to change it if needed, but if someone doesn't know the syntax for docker time zones, it doesn't bork their docker-compose file and at least has a general time zone. Perhaps I should change it to UTC time.

**Comment by leightonc1** [comment]
That's almost exactly what I did to fix, but instead I just did a search for "TZ=America/Chicago" on the script and changed it there rather than directly on the docker-compose file. Maybe there could be another question in the script to specify the timezone in IANA format?
