### ISSUE TITLE
Change Install Path

### ISSUE THREAD

**Issue by leightonc1** [LordZeuss/auto-authelia#4]
It'd be nice to be asked for an installation path in the script. I was able to edit it easily enough by replacing all instances of "/home/$USER/auto-authelia/" with my own path, but this should be fairly easy to automate.

**Comment by LordZeuss** [comment]
Yes, this is a pretty easy fix. I'll work on adding that here shortly. Thanks for pointing that out!

**Comment by leightonc1** [comment]
Thanks! This script made my life much easier rather than having to dig through documentation to configure a basic setup.

**Comment by LordZeuss** [comment]
Feature added.
